from_latest_tag = false
ignore_merge_commits = false
branch_whitelist = []
pre_bump_hooks = [
    "sh -c 'Misc/Scripts/validate_swiftlint.sh'",
    "sh -c 'Misc/Scripts/validate_swiftformat.sh'"
]
post_bump_hooks = [
    "git push",
    "git push remote {{version}}"
]

[commit_types]
wip = { changelog_title = "wip" }

[changelog]
path = "CHANGELOG.md"
template = "changelog_template"
remote = "github.com"
repository = "AnimeNow"
owner = "AnimeNow-Team"
authors = [
    { username = "ErrorErrorError", signature = "ErrorErrorError" }
]

[bump_profiles]