name: CD

on:
  workflow_run:
    workflows: 
      - CI
    types:
      - completed

jobs:
  setup:
    runs-on: macos-12
    if: "${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.head_commit.message, 'chore(version)') }}"
    outputs:
      git_sha: ${{ steps.info.outputs.git_sha }}
      semantic_version: ${{ steps.info.outputs.semantic_version }}
      prerelease: ${{ steps.info.outputs.prerelease }}
      release_notes: ${{ steps.release-notes.outputs.release_notes_body }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Build Info
        id: info
        run: |
          echo "semantic_version=$(git tag -l --sort -creatordate | head -1)" >> $GITHUB_OUTPUT
          echo "git_sha=$(git rev-list --abbrev-commit -n $semantic_version)" >> $GITHUB_OUTPUT
          echo "prerelease='${{ contains($semantic_version, 'beta') }}'" >> $GITHUB_OUTPUT

      - name: Generate release notes
        id: release-notes
        run: |
          brew install cocogitto
          latest_tag=$(git tag -l --sort -creatordate | head -1)
          echo "release_notes=\"$(cog changelog -a $latest_tag)\"" >> $GITHUB_OUTPUT

  build:
    needs: [setup]
    strategy:
      matrix: 
        include:
          - platform: iOS
            extension: ipa
          - platform: macOS
            extension: dmg
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Commit & Semantic Version
        run: |
          sed -i '' 's/\(^COMMIT = \).*/\1${{ needs.setup.outputs.git_sha }}/' ./App/MainConfig.xcconfig
          sed -i '' 's/\(^MARKETING_VERSION = \).*/\1${{ needs.setup.outputs.semantic_version }}/' ./App/MainConfig.xcconfig

      - name: Archive
        run: |
          pushd App
          xcodebuild archive \
            -destination "generic/platform=${{ matrix.platform }}" \
            -scheme "Anime Now!" \
            -archivePath "./Anime Now! (${{ matrix.platform }}).xcarchive" \
            -xcconfig "./MainConfig.xcconfig" \
            CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY= CODE_SIGN_ENTITLEMENTS= GCC_OPTIMIZATION_LEVEL=s SWIFT_OPTIMIZATION_LEVEL=-O
          popd

      - name: Construct ipa
        if: ${{ matrix.platform == 'iOS' }}
        run: |
          pushd App
          mkdir -p "./Payload"
          mv "./Anime Now! (iOS).xcarchive/Products/Applications/Anime Now!.app" "./Payload/Anime Now!.app"
          zip -r "./Anime Now! (iOS).ipa" './Payload'
          rm -rf "./Payload"
          rm -rf "./Anime Now! (iOS).xcarchive"
          popd

      - name: Construct dmg
        if: ${{ matrix.platform == 'macOS' }}
        run: |
          pushd App
          brew install create-dmg
          create-dmg \
            --volname "Anime Now!" \
            --background "../Misc/Media/dmg_background.png" \
            --window-pos 200 120 \
            --window-size 660 400 \
            --icon-size 160 \
            --icon "Anime Now!.app" 180 170 \
            --hide-extension "Anime Now!.app" \
            --app-drop-link 480 170 \
            --no-internet-enable \
            "./Anime Now! (macOS).dmg" \
            "./Anime Now! (macOS).xcarchive/Products/Applications/"
          popd

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: './App/Anime Now! (${{ matrix.platform }}).${{ matrix.extension }}'
          if-no-files-found: error

  publish:
    runs-on: macos-12
    needs: [setup, build]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3

      - name: Release to GitHub
        id: release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: |
            */*
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: false
          prerelease: ${{ needs.setup.outputs.prerelease == 'true' }}
          body: ${{ needs.setup.outputs.release_notes }}
          name: v${{ needs.setup.outputs.semantic_version }}
          tag_name: ${{ needs.setup.outputs.semantic_version }}
