name: Lint code

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  swiftlint-and-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint code using SwiftLint
        run: |
          swiftlint lint --strict --reporter github-actions-logging
