name: Lint

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  run-swiftlint:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Lint code using SwiftLint
        run: |
          swiftlint lint --strict --reporter github-actions-logging
